----WINDOW SIZE---
---- 21----
406750 406750 406750
Created Windows !
Length: 406750
2209 2209 2209
Created Windows !
Length: 2209
Started scaling!
StandardScaler(copy=True, with_mean=True, with_std=True)
Splitting into Test and Train
Training Data is distributed as follows: [(0, 220688), (1, 51782), (2, 52)]
Testing Data is distributed as follows: [(0, 108549), (1, 25649), (2, 30)]
Fitted Model !
Now saving model and scaler
[[52561 34899 21089]
 [ 5487 17119  3043]
 [    0     0    30]]
                   pre       rec       spe        f1       geo       iba       sup

          0       0.91      0.48      0.79      0.63      0.62      0.37    108549
          1       0.33      0.67      0.68      0.44      0.67      0.45     25649
          2       0.00      1.00      0.82      0.00      0.91      0.83        30

avg / total       0.80      0.52      0.77      0.59      0.63      0.39    134228

array([[0.24094913, 0.67704304, 0.08200784],
       [0.34020854, 0.50911366, 0.1506778 ],
       [0.54588926, 0.3313481 , 0.12276265],
       ...,
       [0.23811806, 0.44346507, 0.31841687],
       [0.36830466, 0.19341412, 0.43828122],
       [0.31064558, 0.12036548, 0.56898894]])
/usr/local/lib/python2.7/dist-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
----WINDOW SIZE---
---- 21----
406750 406750 406750
Created Windows !
Length: 406750
2209 2209 2209
Created Windows !
Length: 2209
Started scaling!
StandardScaler(copy=True, with_mean=True, with_std=True)
Splitting into Test and Train
Training Data is distributed as follows: [(0, 220688), (1, 51782), (2, 52)]
Testing Data is distributed as follows: [(0, 108549), (1, 25649), (2, 30)]
Fitted Model !
Now saving model and scaler
[[52561 34899 21089]
 [ 5487 17119  3043]
 [    0     0    30]]
[[96458 12091     0]
 [12510 13139     0]
 [   26     4     0]]
                   pre       rec       spe        f1       geo       iba       sup

          0       0.91      0.48      0.79      0.63      0.62      0.37    108549
          1       0.33      0.67      0.68      0.44      0.67      0.45     25649
          2       0.00      1.00      0.82      0.00      0.91      0.83        30

avg / total       0.80      0.52      0.77      0.59      0.63      0.39    134228

             precision    recall  f1-score   support

          0       0.88      0.89      0.89    108549
          1       0.52      0.51      0.52     25649
          2       0.00      0.00      0.00        30

avg / total       0.82      0.82      0.82    134228

/usr/local/lib/python2.7/dist-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python2.7/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
----WINDOW SIZE---
---- 21----
406750 406750 406750
Created Windows !
Length: 406750
2209 2209 2209
Created Windows !
Length: 2209
Started scaling!
StandardScaler(copy=True, with_mean=True, with_std=True)
Splitting into Test and Train
Training Data is distributed as follows: [(0, 220688), (1, 51782), (2, 52)]
Testing Data is distributed as follows: [(0, 108549), (1, 25649), (2, 30)]
Fitted Model !
Now saving model and scaler
Traceback (most recent call last):
  File "predict_model.py", line 165, in <module>
    main()
  File "predict_model.py", line 44, in main
    bagClassify(sys.argv[1])
  File "predict_model.py", line 123, in bagClassify
    joblib.dump(bbc, 'bag_model.pkl')
NameError: global name 'bbc' is not defined
----WINDOW SIZE---
---- 21----
406750 406750 406750
Created Windows !
Length: 406750
2209 2209 2209
Created Windows !
Length: 2209
Started scaling!
StandardScaler(copy=True, with_mean=True, with_std=True)
Splitting into Test and Train
Training Data is distributed as follows: [(0, 220688), (1, 51782), (2, 52)]
Testing Data is distributed as follows: [(0, 108549), (1, 25649), (2, 30)]
Fitted Model !
Now saving model and scaler
[[98748  9801     0]
 [13265 12384     0]
 [   28     2     0]]
[[98748  9801     0]
 [13265 12384     0]
 [   28     2     0]]
[[100675   7874      0]
 [ 14436  11213      0]
 [    29      1      0]]
             precision    recall  f1-score   support

          0       0.88      0.91      0.90    108549
          1       0.56      0.48      0.52     25649
          2       0.00      0.00      0.00        30

avg / total       0.82      0.83      0.82    134228

             precision    recall  f1-score   support

          0       0.88      0.91      0.90    108549
          1       0.56      0.48      0.52     25649
          2       0.00      0.00      0.00        30

avg / total       0.82      0.83      0.82    134228

             precision    recall  f1-score   support

          0       0.87      0.93      0.90    108549
          1       0.59      0.44      0.50     25649
          2       0.00      0.00      0.00        30

avg / total       0.82      0.83      0.82    134228

/usr/local/lib/python2.7/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'read_mtx': [Errno 2] No such file or directory
/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'read_mtx': [Errno 2] No such file or directory
406750 406750 406750
Traceback (most recent call last):
  File "encode.py", line 253, in <module>
    main()
  File "encode.py", line 32, in main
    encode_MTX(sys.argv[1], str(sys.argv[3]))
  File "encode.py", line 227, in encode_MTX
    X = create_windows(pssm,lengths)
  File "encode.py", line 237, in create_windows
    boundaries = [math.log(background)]*20 + [log(1)]
NameError: global name 'log' is not defined
2209 2209 2209
Traceback (most recent call last):
  File "encode.py", line 253, in <module>
    main()
  File "encode.py", line 32, in main
    encode_MTX(sys.argv[1], str(sys.argv[3]))
  File "encode.py", line 227, in encode_MTX
    X = create_windows(pssm,lengths)
  File "encode.py", line 237, in create_windows
    boundaries = [math.log(background)]*20 + [log(1)]
NameError: global name 'log' is not defined
Invalid Entry!
Expect arguments in format <python sieveson.py JSONFILE function> 
Invalid Entry!
Expect arguments in format <python sieveson.py JSONFILE function> 
406750 406750 406750
Traceback (most recent call last):
  File "encode.py", line 253, in <module>
    main()
  File "encode.py", line 32, in main
    encode_MTX(sys.argv[1], str(sys.argv[3]))
  File "encode.py", line 227, in encode_MTX
    X = create_windows(pssm,lengths)
  File "encode.py", line 237, in create_windows
    boundaries = [math.log(background)]*20 + [log(1)]
NameError: global name 'log' is not defined
2209 2209 2209
Traceback (most recent call last):
  File "encode.py", line 253, in <module>
    main()
  File "encode.py", line 32, in main
    encode_MTX(sys.argv[1], str(sys.argv[3]))
  File "encode.py", line 227, in encode_MTX
    X = create_windows(pssm,lengths)
  File "encode.py", line 237, in create_windows
    boundaries = [math.log(background)]*20 + [log(1)]
NameError: global name 'log' is not defined
Invalid Entry!
Expect arguments in format <python sieveson.py JSONFILE function> 
Invalid Entry!
Expect arguments in format <python sieveson.py JSONFILE function> 
Traceback (most recent call last):
  File "encode.py", line 253, in <module>
    main()
  File "encode.py", line 32, in main
    encode_MTX(sys.argv[1], str(sys.argv[3]))
  File "encode.py", line 224, in encode_MTX
    pssm = mtxCompressed['pssm']
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 239, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'pssm is not a file in the archive'
2209 2209 2209
Traceback (most recent call last):
  File "encode.py", line 253, in <module>
    main()
  File "encode.py", line 32, in main
    encode_MTX(sys.argv[1], str(sys.argv[3]))
  File "encode.py", line 227, in encode_MTX
    X = create_windows(pssm,lengths)
  File "encode.py", line 237, in create_windows
    boundaries = [math.log(background)]*20 + [log(1)]
NameError: global name 'log' is not defined
